### ISSUE TITLE
Durable Functions 2.1 Release Checklist

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1102]
As part of a release, the following items need to be taken care of. For any items that are not applicable, they should be crossed out using the `~~ ~~` markdown syntax with an explanation.

- [x] Close out or punt remaining GitHub issues for the current milestone
- [x] Run private scale tests and ensure no regressions
- [x] Publish updated versions of [DurableTask.Core](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/) and [DurableTask.AzureStorage](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/) to nuget.org
- [x] Merge all features and fixes into the `master` branch
- [x] Publish signed version of [Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/) to nuget.org
- [x] Update samples to point to the latest nuget packages
- ~~[ ] Create a PR in the [Azure Functions templates repo](https://github.com/Azure/azure-functions-templates) to update templates to the latest version~~ _(No templates for 2.x yet)_
- ~~[ ] Create a PR in the [Azure Functions bundles repo](https://github.com/Azure/azure-functions-extension-bundles) to update bundles to the latest version~~ _(No bundles for 2.x yet)_
- [x] Publish release notes
- [x] Update official docs under https://docs.microsoft.com/en-us/azure/azure-functions/durable ([private docs repo for Microsoft employees](http://github.com/MicrosoftDocs/azure-docs-pr))
- [x] Post announcement on Twitter.

**Comment by mpaul31** [comment]
@cgillum is the plan to still publish a release early this week?

**Comment by cgillum** [comment]
@mpaul31 yep - we just have a couple lingering PRs that need to be merged first.

**Comment by cgillum** [comment]
The v2.1.0 release is done!
* Release notes: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.1.0
* Tweet: https://twitter.com/cgillum/status/1207921660554182657
