### ISSUE TITLE
2.7.0 release checklist

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#2138]
**Prep DTFx Release: (assigned to: @cgillum)**

- [x] Check DTFx package versions (either DT-AzureStorage only or if there were Core changes DT-AzureStorage, DT-Core, DT-Emulator, and DT-Redis)
- [x] Delete DTFx test packages from staging myget.
- [x] Publish DTFx packages to staging myget for testing. (either DT-AzureStorage only or if there were Core changes DT-AzureStorage and DT-Core)

**Prep Release (assigned to: @cgillum)**
_Due: <2-business-days-before-release>_
- [x] Update Durable Functions references (Analyzer? DTFx?) and check current version.
- [x] Locally, run `dotnet list package --vulnerable` to ensure the release is not affected by any vulnerable dependencies.
- [x] Add Durable Functions package to myget staging feed.
- [x] Check for package size, make sure it's not surprisingly heavier than a previous release.
  - The size increased from ~500 KB to about ~830 KB, likely because of the new .NET 6 target, in which case this is expected.
- [x] Merge dev into main. Person performing validation must approve PR. Important: Merge NOT Squash merge.

**Validation**
_Due: <1-business-days-before-release>_
- [x] Run private performance tests and ensure no regressions. **(assigned to: @cgillum)**
- [x] Smoke test Functions V1, Functions V2, and Functions V3 .NET apps. **(assigned to: @cgillum)**
  - [x] Functions V1
  - [x] Functions V2
  - [x] Functions V3 (this is automated by the CI)
  - [x] Functions V4
  - [x] Functions V4 - .NET Isolated
- [x] Smoke test JavaScript and Python apps. **(assigned to: @cgillum)**
  - [x] JavaScript (this is automated by the CI)
  - [x] Python
      - https://github.com/Azure/azure-functions-durable-python/issues/368)

**DTFx Release Completion (assigned to: @cgillum)**
_Due: <release-deadline>_
- [x] Publish DTFx packages to nuget (directly to nuget.org).
- [x] Publish release notes for DTFx.
- [ ] Patch increment DTFx packages that were released

**Release Completion (assigned to: )**
_Due: <release-deadline>_
- [x] Delete Durable Functions packages from myget.
- [x] Run Durable Functions release pipeline.
- [x] Push myget package to nuget (nuget.org extensions package option).
- [ ] Create a PR in the [Azure Functions templates repo](https://github.com/Azure/azure-functions-templates) targeting branch `v3.x` to update *only the dotnet* templates (`template.json` files) to the latest version.
- [ ] Create a PR in the [Azure Functions templates repo](https://github.com/Azure/azure-functions-templates) targeting branch `v4.x` to update *only the dotnet* templates (`template.json` files) to the latest version.
- [x] ~~_if and only if this is a new major release_, Create a PR in the [Azure Functions bundles repo](https://github.com/Azure/azure-functions-extension-bundles) to update bundles to the latest version .~~
- [x] Merge all pending PR docs from `pending_docs.md.`
- [x] Reset `pending_docs.md` and `release_notes.md` in the `dev` branch. You will want to save `release_notes.md` somewhere for when you publish release notes.
- [x] Publish release notes from the pre-reset `release_notes.md.`
- [x] Post announcement on [App Service Announcements GitHub repo](https://github.com/Azure/app-service-announcements) and Twitter (Chris).
- [x] Increment Durable Functions patch version.

**Comment by davidmrdavid** [comment]
Before completing these, @cgillum , please consider this PR - https://github.com/Azure/azure-functions-durable-extension/pull/2146 .

I'm also updating our internal release thread with context.

**Comment by cgillum** [comment]
Release is posted: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.7.0
