### ISSUE TITLE
Distributed Tracing GA work items

### ISSUE THREAD

**Issue by bachuv** [Azure/azure-functions-durable-extension#2660]
```[tasklist]
### Tasks
- [ ] Correlate parent function with orchestration functions for .NET Isolated apps (#2662, #2798)
- [ ] Correlate parent function with orchestration functions for non-.NET apps (Need to test all OOProc languages)
- [ ] Update templates so that they enable Distributed Tracing V2 by default
- [ ] Fix distributed tracing tests in DTFx repo (the tests that include OpenTelemetry in the title are failing)
- [ ] https://github.com/Azure/azure-functions-durable-extension/issues/2870
- [ ] Investigate long response times when extended sessions is enabled with DT V2 (#2749)
```

**Comment by gha-zund** [comment]
we are eagerly waiting for entity support on isolated functions!

**Comment by jviau** [comment]
> * Add support for [Baggage property](https://opentelemetry.io/docs/concepts/signals/baggage/#:~:text=In%20OpenTelemetry%2C%20Baggage%20is%20contextual%20information%20that%E2%80%99s%20passed,available%20to%20any%20span%20created%20within%20that%20trace.) to share information between spans

Baggage implementation: https://github.com/Azure/durabletask/issues/1073 -- But with that said, I don't think this is actually needed for GA.

**Comment by mohitgadkar** [comment]
any update on DT v2 for isolated functions. I am still facing same issue DT not linking parent function to activity.

**Comment by lilyjma** [comment]
@mohitgadkar - We're aiming to wrap up this feature next month. Thanks for your patience!

**Comment by BOLT04** [comment]
hi everyone, I recently saw in my logs "Durable Functions Distributed Tracing V2 is GA now!". I then checked and saw this PR merged: #3127

Are the work items of this issue all done? Meaning is DT V2 already GA?
If it is, does anyone know if there will be a blog post or announcement from the Microsoft team?

Thanks in advance!

**Comment by mohitgadkar** [comment]
Hello Team, Any update on this?

Thanks
Mohit

**Comment by bachuv** [comment]
Distributed Tracing V2 is GA and available in the following packages:

- For .NET Isolated apps, Distributed Tracing V2 requires [Microsoft.Azure.Functions.Worker.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask) >= v1.4.0.
- For non-.NET apps, [follow these instructions](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-extension-upgrade#manually-upgrade-the-durable-functions-extension) to manually install [Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask) >= v3.2.0 for now. You won't need to take this step when extension bundles [v4.25.0](https://github.com/Azure/azure-functions-extension-bundles/releases) is available.

We'll publish an official announcement after extension bundles v4.25.0 is released so that non-.NET customers don't need to manually install the extension. The bundles release is expected to finish in a few weeks.

For supported features and more information, please visit [Diagnostics in Durable Functions - Azure | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp-inproc#distributed-tracing). I also updated this GitHub issue with the issues and PRs that were a part of this release.

**Comment by lilyjma** [comment]
@BOLT04 - in case you aren't aware, there's an Azure Update that went out about the GA https://azure.microsoft.com/en-us/updates/?id=503139. @bachuv is working on the blog post.
