### ISSUE TITLE
Durable Functions V3 GA work items

### ISSUE THREAD

**Issue by nytian** [Azure/azure-functions-durable-extension#2822]
```[tasklist]
### Tasks
- [x] Update branch `azure-storage-track2` with `main` in DTFx.
- [x] Update branch `v3.x` with `main` in DF extension.
- [x] Bug fixes about pop-receipt.
- [x] Update deprecated/security vulnerable dependencies version to the latest, including Azure.Identity v1.10.0
- [ ] Official documents update: drop support on v1; v2 will be in maintenance; new features will only be added in v3.
- [x] Performance Tests on .NET isolated worker
- [x] Verify if we have memory leak issue with managed identity as durable v2
- [x] .NET 6 framework updates
- [x] DTFx.AS v2 forward compatibility support and DTFx.AS v1 backward compatibility support
- [x] Remove .NET Framework 4.6.2 from DT.AS and DT.Core
- [x] Update Scale Controller v2 and v3 to use DTFx.AzureStorage v2 package
```

```[tasklist]
### Tasks
```

**Comment by nytian** [comment]
New preview version has been released:

DTFx.Azrue Storage: https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v2.0.0-rc.2
Durable in-proc Extension: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v3.0.0-rc.2
Worker Extension:  https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.2.0-rc.2Worker.Extensions.DurableTask

This preview version includes:

- Bug fixes at pop receipt.
- Update durable v3 with durable v2 by using the latest DTFx.Core v2.17.1 and DTFx. ApplicationInsights 0.1.6.
- Update deprecated SDK, eg Azure.Identity.

**Comment by nytian** [comment]
New preview version released:

https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/2.0.0-rc.3

This new version add support to enable forward compatibility with DTFx.AzureStorage v1.x.

**Comment by nytian** [comment]
DurableTask package has been officially released. 

[NuGet Gallery | Microsoft.Azure.DurableTask.AzureStorage 2.0.0](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/2.0.0)
[NuGet Gallery | Microsoft.Azure.DurableTask.Core 3.0.0](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/3.0.0)

**Comment by nytian** [comment]
DF v3 package will be released after Scale Controller v2.x and v3.x are both released.

**Comment by nytian** [comment]
Currently waiting for SC to release.

**Comment by nytian** [comment]
Completed as packages released .

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/3.0.0
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.2.0
